### ISSUE TITLE
How to get UA-XXXXXXX after creating Firebase app?

### ISSUE THREAD

**Issue by mathiasjakobsen** [jaystack/electron-ga#1]
I want to use your library, but after I created an app in Firebase I can't find a UA-XXXXXX token anywhere. Where did you obtain this?

**Comment by cpsloal** [comment]
UA-XXXXXXX-X is a Google Analytics concept. Head over to https://analytics.google.com and signup (and select mobile app when creating a project on GA).

**Comment by mathiasjakobsen** [comment]
@cpsloal I get that, but the README says to create a [Google Analytics Mobile Account](https://developers.google.com/analytics/solutions/mobile). When I do that, in Google Analytics, it prompts me to create a Firebase app to proceed. When this is done, I can select that app over in Analytics and activate tracking on it - but there's no tracking ID like there usually is?

**Comment by mathiasjakobsen** [comment]
The reason for the Android icon, is that one MUST select either iOS or Android as platform when activating tracking in Firebase - and if I select iOS i MUST enter a registered app ID, which I, obviously, don't have for my Electron app.

**Comment by hz0324** [comment]
@mathiasjakobsen hi, have you got it through? I am facing the same problem now. Please help.

**Comment by mathiasjakobsen** [comment]
@hz0324 Nope, I havn't :(

**Comment by cpsloal** [comment]
@hz0324 @mathiasjakobsen I went to GA portal (https://analytics.google.com) and created JS/Web tracking to get the UA-XXXXXXX-X tracking ID.  Hope that helps.

![ga](https://user-images.githubusercontent.com/355905/39054004-536b324a-44d2-11e8-890d-536497b3dbeb.png)
![ua2](https://user-images.githubusercontent.com/355905/39054005-53b124e4-44d2-11e8-8641-44033bd3f118.png)

**Comment by apolkingg8** [comment]
@cpsloal Hi, did you get this project worked with a web/js tracking page? I got the UA-XXXXXXX-X tracking ID and send event successfully in render process, but nothing shown on the GA web page.

**Comment by cpsloal** [comment]
@apolkingg8 I did get it working.  Try the real-time reports.  Events take a while to show-up in regular GA reports.

**Comment by ganeshrvel** [comment]
If anyone is still looking for the answer this link might help: https://stackoverflow.com/a/44467365/1317099

**Comment by phamquanghungkma** [comment]
I have the same problem, who can help me ?

**Comment by SteFF1997** [comment]
I don't have a web site at my project, I have only mobile. Why I need to create web app at analytics???
Why firebase organized everything so stupidly?????

**Comment by shalomfriss** [comment]
Looks like if you're using app+web measurement id is used instead https://support.google.com/analytics/answer/7372977

**Comment by Parag547** [comment]
> @hz0324 @mathiasjakobsen I went to GA portal (https://analytics.google.com) and created JS/Web tracking to get the UA-XXXXXXX-X tracking ID. Hope that helps.
> 
> ![ga](https://user-images.githubusercontent.com/355905/39054004-536b324a-44d2-11e8-890d-536497b3dbeb.png)
> ![ua2](https://user-images.githubusercontent.com/355905/39054005-53b124e4-44d2-11e8-8641-44033bd3f118.png)
  
@cpsloal Did you register a web property for an electron application? if yes then what did you add in the url section where we need to add a http url because I'm not sure if we can have that for an electron application. Basically I need help to add data stream for an electron application while registering a property.
